FROM nginx:latest
LABEL contributor="Owen O. Phakade <olwethuphakade89@gmail.com>"

RUN useradd -U app_user

RUN install -d -m 0755 -o app_user -g app_user /usr/share/nginx/staticfiles \
    && install -m 0644 -o app_user -g app_user /dev/null /var/run/nginx.pid

COPY --chown=app_user:app_user ./nginx/templates /etc/nginx/templates
COPY --chown=app_user:app_user ./nginx/nginx.conf /etc/nginx/nginx.conf

RUN chown -R app_user:app_user \
    /var/cache/nginx \
    /var/log/nginx \
    /etc/nginx/conf.d

USER app_user:app_user

CMD ["nginx", "-g", "daemon off;"]