version: '3.1'

services:
  app:
    container_name: django_container
    image: django_app:latest
    expose:
      - 8000
    env_file:
      - ./.env/django.env
    volumes:
      - django_static_volume:/app/staticfiles
  web:
    container_name: nginx_container
    image: django_web:latest
    ports:
      - 80:80
    depends_on:
      - app
    env_file:
      - ./.env/nginx.env
    volumes:
      - django_static_volume:/usr/share/nginx/staticfiles
      
volumes:
  django_static_volume: