version: '3.1'

services:
  app:
    container_name: django_container
    image: django_app:latest
    expose:
      - 8000
    env_file:
      - ./.env/django.env
    volumes:
      - django_static_volume:/app/staticfiles
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  web:
    container_name: nginx_container
    image: django_web:latest
    ports:
      - 8080:80
    env_file:
      - ./.env/nginx.env
    volumes:
      - django_static_volume:/usr/share/nginx/staticfiles
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    depends_on:
      - app
  db:
    container_name: postgres_container
    image: postgres
    env_file:
      - ./.env/postgres.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
volumes:
  django_static_volume: