# Generated by Django 4.2.4 on 2023-08-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ability', serialize=False, to='characters.character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='characters.character'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='characters.character'),
        ),
    ]
