name: Tekken7-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environ: test
      image_tag: ${GITHUB_REPOSITORY}:${GITHUB_RUN_NUMBER}
    secrets:
      aws-account-id: ${{ secrets.ACCOUNT_ID }}
      aws_region: ${{ secrets.AWS_REGION}}
      snyk_token: ${{ secrets.SNYK_TOKEN }}
      tekken7-oidc-role-arn: ${{ secrets.AWS_TEKKEN7_OIDC_ROLE_ARN }}
