name: Tekken7-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environ: test
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
  
