name: Tekken7-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-env:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environ: test
      aws-ecr-repository: ${{ github.repository }}
      version_tag: ${{ github.run_number }} 
    secrets:
      aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}